# Generated by Django 4.0.4 on 2022-05-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_home_phnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='age',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='home',
            name='mailid',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='home',
            name='phnumber',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='home',
            name='prof',
            field=models.CharField(max_length=122),
        ),
    ]
