# Generated by Django 4.0.4 on 2022-05-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_home_age_alter_home_mailid_alter_home_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='age',
            field=models.CharField(default='12', max_length=122),
        ),
        migrations.AlterField(
            model_name='home',
            name='mailid',
            field=models.CharField(default='xyz@mail.com', max_length=122),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(default='name', max_length=122),
        ),
        migrations.AlterField(
            model_name='home',
            name='phnumber',
            field=models.CharField(default='91', max_length=122),
        ),
        migrations.AlterField(
            model_name='home',
            name='prof',
            field=models.CharField(default='asdd', max_length=122),
        ),
    ]
