# Generated by Django 4.0.4 on 2022-05-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_newschedule_alter_home_age_alter_home_mailid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newschedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='newschedule',
            name='time',
        ),
        migrations.RemoveField(
            model_name='newschedule',
            name='title',
        ),
    ]
