# Generated by Django 4.0.4 on 2022-05-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_newschedule_name_alter_home_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschedule',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
